"""Destination connector interface and configurable mock implementation."""

from services.connectors.base import (
    ActionReference,
    AttributionSurface,
    ConfirmationConnector,
    ConnectorCapabilities,
    ConnectorCapabilityError,
    ConnectorContractError,
    ConnectorScope,
    DestinationConnector,
    EnumerationConnector,
    EnumerationUnusableError,
    EnumerationWindow,
    SettlementLagExceededError,
    WindowCoverageUnavailableError,
    enumerate_for_window_coverage,
    require_confirmer,
    require_window_enumerator,
)
from services.connectors.mock import (
    MockCapabilityConfigurationError,
    MockConfirmationConnector,
    MockConnectorConfig,
    MockDestinationRecord,
    MockEnumerationConnector,
    MockFullConnector,
    SilentTruncationError,
    create_mock_connector,
)

__all__ = [
    "ActionReference",
    "AttributionSurface",
    "ConfirmationConnector",
    "ConnectorCapabilities",
    "ConnectorCapabilityError",
    "ConnectorContractError",
    "ConnectorScope",
    "DestinationConnector",
    "EnumerationConnector",
    "EnumerationUnusableError",
    "EnumerationWindow",
    "MockCapabilityConfigurationError",
    "MockConfirmationConnector",
    "MockConnectorConfig",
    "MockDestinationRecord",
    "MockEnumerationConnector",
    "MockFullConnector",
    "SettlementLagExceededError",
    "SilentTruncationError",
    "WindowCoverageUnavailableError",
    "create_mock_connector",
    "enumerate_for_window_coverage",
    "require_confirmer",
    "require_window_enumerator",
]
