"""Synchronous evidence ingestion and issuer-authored receipt primitives."""

from .receipts import (
    KeyNamespaceError,
    NonCanonicalWireError,
    ReceiptError,
    ReceiptSignatureError,
    RegisteredPublicKey,
    SignedIngestionReceipt,
    create_ingestion_receipt,
    measure_clock_skew_ms,
    parse_canonical_record_wire,
    parse_timestamp,
    verify_canonical_evidence_record,
    verify_evidence_record_signature,
    verify_ingestion_receipt,
    verify_record_origin_signature,
)
from .service import (
    ChainConflictError,
    CollectorAuthenticationError,
    ContentSubstitutionError,
    ForkIntegrityError,
    IngestionAcknowledgement,
    IngestionError,
    IngestionService,
    IssuerSigningKey,
    LedgerUnavailableError,
    ReplayError,
)

__all__ = [
    "ChainConflictError",
    "CollectorAuthenticationError",
    "ContentSubstitutionError",
    "ForkIntegrityError",
    "IngestionAcknowledgement",
    "IngestionError",
    "IngestionService",
    "IssuerSigningKey",
    "KeyNamespaceError",
    "LedgerUnavailableError",
    "NonCanonicalWireError",
    "RegisteredPublicKey",
    "ReplayError",
    "ReceiptError",
    "ReceiptSignatureError",
    "SignedIngestionReceipt",
    "create_ingestion_receipt",
    "measure_clock_skew_ms",
    "parse_timestamp",
    "parse_canonical_record_wire",
    "verify_canonical_evidence_record",
    "verify_evidence_record_signature",
    "verify_record_origin_signature",
    "verify_ingestion_receipt",
]
