"""Alembic environment for the evidence ledger.

Online mode only. Offline (`--sql`) generation is deliberately unsupported:
these migrations create roles and grants, and a generated script applied by
hand is exactly the unlogged schema path SE-012 and SE-024 rule out.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from services.ledger import LedgerConfig

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Migrations run under the migrator credential -- the owner of the schema,
# and the only role that may run DDL (SE-012 §6).
config.set_main_option(
    "sqlalchemy.url",
    LedgerConfig.from_env().migrator_url.render_as_string(hide_password=False),
)

# No autogenerate: partitioning, role grants and the projection rebuild are
# not expressible as metadata diffs, and a partial autogenerated migration
# would look complete.
target_metadata = None


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    raise RuntimeError(
        "offline migration generation is not supported: these migrations "
        "manage roles and grants and must be applied through the audited "
        "online path (SE-012, SE-024)"
    )

run_migrations_online()
