"""Acceptance for EV-22: QA-S-001, asserted through the command-line interface.

QA-S-001 is EV-22's acceptance scenario:

    Given a new assertion added to the catalogue
    And no scenario referencing it
    When CI runs
    Then the traceability check fails
    And the failure names the unmapped assertion

These assert through the CLI -- exit status and printed output -- rather than by
reaching into the Matrix object, because the CLI is what CI runs and an
assertion against internal state would not catch a gate wired up wrongly. That
is the spirit of AG-006 and QA-S-005.

The corpora live under `fixtures/` rather than inline in this module, so that
the fictional 400-block requirement IDs never appear in Python source. The
matrix reads IDs in test files as citations; writing the fixture inline would
make this module report its own fixture data as retired references.

Why this is not a pytest-bdd binding
------------------------------------
It should be `@scenario("meta.feature", "QA-S-001 ...")`. It cannot be, yet:
`tests/features/meta.feature` is not parseable Gherkin. Line 16 reads

    @QA-S-002 @QA-005 property 6

because `testing-qa.md:158` heads that scenario `*(QA-005 property 6)*` and
`extract_features.py` splits the reference list on commas only, so the prose
"property 6" is emitted as two further tags -- and a Gherkin tag may not contain
whitespace. pytest-bdd refuses the whole file, so no step definition can bind to
any QA-S-nnn scenario. Nothing caught this because `--check` only compares
generated bytes against what is on disk, and until now no test tried to load the
feature.

Both fixes -- the heading in `docs/testing-qa.md`, or comma-splitting in
`tools/extract_features.py` -- are outside EV-22's Touches set, so this story
reports the defect rather than fixing it (AG-015). The matrix detects the class
directly: see MALFORMED_SCENARIO_REF, which fires on `testing-qa.md:158` in the
live run. Once the heading is corrected and the feature regenerates, the first
test below should become a `@scenario` binding and QA-S-001 stops being an
untested scenario.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from tests.traceability.matrix import main

FIXTURES = Path(__file__).parent / "fixtures"


def _corpus(tmp_path: Path, name: str) -> Path:
    """Copy a fixture corpus somewhere writable and give it an empty collection."""
    shutil.copytree(FIXTURES / name, tmp_path / name)
    root = tmp_path / name
    (root / "collected.txt").write_text("", encoding="utf-8")
    return root


def _run(root: Path, *extra: str) -> int:
    return main(
        [
            "--repo-root", str(root),
            "--docs", str(root / "docs"),
            "--features", str(root / "no-features"),
            "--collect-from", str(root / "collected.txt"),
            *extra,
        ]
    )


def test_qa_s_001_assertion_without_scenario_fails_ci(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """An assertion nothing demonstrates must stop the build, and be named."""
    root = _corpus(tmp_path, "assertion_without_scenario")

    code = _run(root, "--mode", "enforce", "--fail-on", "critical")
    output = capsys.readouterr().out

    assert code == 1, "an assertion with no scenario must fail the build in enforce mode"
    assert "A-01" in output, "the failure must name the assertion, not merely count it"
    assert "ASSERTION_NO_SCENARIO" in output


def test_report_mode_reports_the_same_finding_and_exits_zero(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The staged gate EV-22 lands behind.

    Report-only must be a difference in consequence, not in detection. A mode
    that also stopped looking would be a disabled gate wearing a flag.
    """
    root = _corpus(tmp_path, "assertion_without_scenario")

    code = _run(root, "--mode", "report")
    output = capsys.readouterr().out

    assert code == 0
    assert "ASSERTION_NO_SCENARIO" in output, "report mode must still find it"
    assert "A-01" in output
    assert "report-only" in output


def test_enforce_respects_the_severity_threshold(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The staging path, exercised: a medium finding, a moving threshold."""
    root = _corpus(tmp_path, "orphan_only")

    code = _run(root, "--mode", "enforce", "--fail-on", "critical")
    output = capsys.readouterr().out
    assert code == 0, "a medium finding must not fail a critical-only gate"
    assert "REQUIREMENT_NO_SCENARIO_SPEC" in output, "but it must still be reported"

    code = _run(root, "--mode", "enforce", "--fail-on", "medium")
    assert code == 1, "the same finding must fail once the threshold reaches it"
