"""Acceptance for EV-22: QA-S-001, asserted through the command-line interface.

QA-S-001 is EV-22's acceptance scenario:

    Given a new assertion added to the catalogue
    And no scenario referencing it
    When CI runs
    Then the traceability check fails
    And the failure names the unmapped assertion

These assert through the CLI -- exit status and printed output -- rather than by
reaching into the Matrix object, because the CLI is what CI runs and an
assertion against internal state would not catch a gate wired up wrongly. That
is the spirit of AG-006 and QA-S-005.

The corpora live under `fixtures/` rather than inline in this module, so that
the fictional 400-block requirement IDs never appear in Python source. The
matrix reads IDs in test files as citations; writing the fixture inline would
make this module report its own fixture data as retired references.

Why this is not a pytest-bdd binding
------------------------------------
It should be `@scenario("meta.feature", "QA-S-001 ...")`. It cannot be, yet:
`tests/features/meta.feature` is not parseable Gherkin. Line 16 reads

    @QA-S-002 @QA-005 property 6

because `testing-qa.md:158` heads that scenario `*(QA-005 property 6)*` and
`extract_features.py` splits the reference list on commas only, so the prose
"property 6" is emitted as two further tags -- and a Gherkin tag may not contain
whitespace. pytest-bdd refuses the whole file, so no step definition can bind to
any QA-S-nnn scenario. Nothing caught this because `--check` only compares
generated bytes against what is on disk, and until now no test tried to load the
feature.

Both fixes -- the heading in `docs/testing-qa.md`, or comma-splitting in
`tools/extract_features.py` -- are outside EV-22's Touches set, so this story
reports the defect rather than fixing it (AG-015). The matrix detects the class
directly: see MALFORMED_SCENARIO_REF, which fires on `testing-qa.md:158` in the
live run. Once the heading is corrected and the feature regenerates, the first
test below should become a `@scenario` binding and QA-S-001 stops being an
untested scenario.
"""

from __future__ import annotations

import shutil
from datetime import date
from pathlib import Path

import pytest

from tests.traceability.matrix import (
    ENFORCEMENT_SCHEDULE,
    Severity,
    effective_threshold,
    main,
    mandated_threshold,
    strictest,
    strictness,
)

FIXTURES = Path(__file__).parent / "fixtures"


def _corpus(tmp_path: Path, name: str) -> Path:
    """Copy a fixture corpus somewhere writable and give it an empty collection."""
    shutil.copytree(FIXTURES / name, tmp_path / name)
    root = tmp_path / name
    (root / "collected.txt").write_text("", encoding="utf-8")
    return root


def _run(root: Path, *extra: str) -> int:
    return main(
        [
            "--repo-root", str(root),
            "--docs", str(root / "docs"),
            "--features", str(root / "no-features"),
            "--collect-from", str(root / "collected.txt"),
            *extra,
        ]
    )


def test_qa_s_001_assertion_without_scenario_fails_ci(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """An assertion nothing demonstrates must stop the build, and be named."""
    root = _corpus(tmp_path, "assertion_without_scenario")

    code = _run(root, "--mode", "enforce", "--fail-on", "critical")
    output = capsys.readouterr().out

    assert code == 1, "an assertion with no scenario must fail the build in enforce mode"
    assert "A-01" in output, "the failure must name the assertion, not merely count it"
    assert "ASSERTION_NO_SCENARIO" in output


def test_report_mode_reports_the_same_finding_and_exits_zero(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The staged gate EV-22 lands behind.

    Report-only must be a difference in consequence, not in detection. A mode
    that also stopped looking would be a disabled gate wearing a flag.
    """
    root = _corpus(tmp_path, "assertion_without_scenario")

    code = _run(root, "--mode", "report")
    output = capsys.readouterr().out

    assert code == 0
    assert "ASSERTION_NO_SCENARIO" in output, "report mode must still find it"
    assert "A-01" in output
    assert "report-only" in output


def test_enforce_respects_the_severity_threshold(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The staging path, exercised: a medium finding, a moving threshold."""
    root = _corpus(tmp_path, "orphan_only")

    code = _run(root, "--mode", "enforce", "--fail-on", "critical")
    output = capsys.readouterr().out
    assert code == 0, "a medium finding must not fail a critical-only gate"
    assert "REQUIREMENT_NO_SCENARIO_SPEC" in output, "but it must still be reported"

    code = _run(root, "--mode", "enforce", "--fail-on", "medium")
    assert code == 1, "the same finding must fail once the threshold reaches it"


# --- QA-011 staged enforcement -------------------------------------------
#
# The schedule is compiled into the generator, not passed on the command line,
# because a ratchet any CI argument can loosen is not a ratchet. These lock the
# dates and the one-way property to the text in docs/testing-qa.md §7.


def test_schedule_matches_the_dates_qa_011_states() -> None:
    """If this fails, the spec and its implementation have drifted apart."""
    assert ENFORCEMENT_SCHEDULE == (
        (date(2026, 8, 8), Severity.CRITICAL),
        (date(2026, 9, 1), Severity.HIGH),
        (date(2026, 10, 1), Severity.LOW),
    )


@pytest.mark.parametrize(
    ("today", "expected"),
    [
        (date(2026, 8, 7), None),
        (date(2026, 8, 8), Severity.CRITICAL),
        (date(2026, 8, 31), Severity.CRITICAL),
        (date(2026, 9, 1), Severity.HIGH),
        (date(2026, 9, 30), Severity.HIGH),
        (date(2026, 10, 1), Severity.LOW),
        (date(2027, 1, 1), Severity.LOW),
    ],
)
def test_mandate_advances_by_date_alone(today: date, expected: Severity | None) -> None:
    """Expiry is by date, not by condition.

    Nothing here consults whether EV-25 merged, whether EV-26 triage finished,
    or whether any backfill happened. Slipping a story does not slip the gate.
    """
    assert mandated_threshold(today) is expected


def test_a_weaker_request_is_overridden_by_the_schedule() -> None:
    """The one-way ratchet. Asking for less than is mandated gets you the mandate."""
    threshold, why = effective_threshold(Severity.CRITICAL, date(2026, 10, 1))
    assert threshold is Severity.LOW
    assert "one-way ratchet" in why


def test_report_only_is_overridden_once_a_stage_is_live() -> None:
    """`--mode report` stops being an escape hatch the moment a date passes."""
    threshold, why = effective_threshold(None, date(2026, 8, 8))
    assert threshold is Severity.CRITICAL
    assert "overridden" in why


def test_a_stronger_request_is_honoured_and_not_walked_back() -> None:
    """Enforcing early is always allowed; the schedule is a floor, not a ceiling."""
    threshold, _ = effective_threshold(Severity.LOW, date(2026, 8, 8))
    assert threshold is Severity.LOW


def test_report_only_is_permitted_only_before_the_first_stage() -> None:
    threshold, why = effective_threshold(None, date(2026, 8, 7))
    assert threshold is None
    assert "before 2026-08-08" in why


def test_the_gate_bites_on_the_expiry_date(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """End to end through the CLI: same corpus, green before, red after."""
    root = _corpus(tmp_path, "assertion_without_scenario")

    assert _run(root, "--mode", "report", "--today", "2026-08-07") == 0
    assert "report-only" in capsys.readouterr().out

    assert _run(root, "--mode", "report", "--today", "2026-08-08") == 1
    output = capsys.readouterr().out
    assert "ASSERTION_NO_SCENARIO" in output
    assert "FAIL" in output


@pytest.mark.parametrize(
    ("real", "supplied"),
    [
        # The window the old sentinel left open: real calendar in the critical
        # stage, supplied date one day before it. Both mapped to rank 0, so the
        # floor never applied and enforcement switched off for all of August.
        (date(2026, 8, 8), date(2026, 8, 7)),
        (date(2026, 8, 9), date(2026, 8, 7)),
        (date(2026, 8, 20), date(2026, 1, 1)),
        (date(2026, 8, 31), date(2026, 8, 7)),
        # And the later stages, which the rank comparison happened to cover.
        (date(2026, 9, 1), date(2026, 8, 8)),
        (date(2026, 10, 1), date(2026, 9, 1)),
    ],
)
def test_today_cannot_disable_a_live_stage_through_the_cli(
    tmp_path: Path, capsys: pytest.CaptureFixture[str], real: date, supplied: date
) -> None:
    """`--today` must never weaken a mandate the real calendar has reached.

    Asserted through the CLI, at the exact point the bypass was reachable. The
    earlier version of this test only compared ranks on 1 October and so never
    touched the one stage that was broken.
    """
    root = _corpus(tmp_path, "assertion_without_scenario")

    code = main(
        [
            "--repo-root", str(root),
            "--docs", str(root / "docs"),
            "--features", str(root / "no-features"),
            "--collect-from", str(root / "collected.txt"),
            "--mode", "report",
            "--today", supplied.isoformat(),
        ],
        real_today=real,
    )
    output = capsys.readouterr().out

    assert code == 1, (
        f"--today {supplied} must not disable the stage live on {real}"
    )
    assert "FAIL" in output
    assert "ASSERTION_NO_SCENARIO" in output


def test_none_ranks_below_every_severity() -> None:
    """The ordering the bypass turned on.

    `None` means "block nothing" and must sit strictly below `critical`. Folding
    it onto CRITICAL is what made a live gate and no gate compare equal.
    """
    assert strictness(None) < strictness(Severity.CRITICAL)
    assert strictness(Severity.CRITICAL) < strictness(Severity.HIGH)
    assert strictness(Severity.HIGH) < strictness(Severity.MEDIUM)
    assert strictness(Severity.MEDIUM) < strictness(Severity.LOW)
    assert strictest(None, Severity.CRITICAL) is Severity.CRITICAL
    assert strictest(None, None) is None


def test_a_future_today_may_still_bring_a_stage_forward(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The legitimate use survives: rehearse September while it is August."""
    root = _corpus(tmp_path, "orphan_only")

    code = main(
        [
            "--repo-root", str(root),
            "--docs", str(root / "docs"),
            "--features", str(root / "no-features"),
            "--collect-from", str(root / "collected.txt"),
            "--mode", "report",
            "--today", "2026-10-01",
        ],
        real_today=date(2026, 8, 1),
    )
    output = capsys.readouterr().out
    assert code == 1, "a medium orphan must fail once the low stage is rehearsed"
    assert "REQUIREMENT_NO_SCENARIO_SPEC" in output
