"""Acceptance for EV-22: QA-S-001, asserted through the command-line interface.

QA-S-001 is EV-22's acceptance scenario:

    Given a new assertion added to the catalogue
    And no scenario referencing it
    When CI runs
    Then the traceability check fails
    And the failure names the unmapped assertion

These assert through the CLI -- exit status and printed output -- rather than by
reaching into the Matrix object, because the CLI is what CI runs and an
assertion against internal state would not catch a gate wired up wrongly. That
is the spirit of AG-006 and QA-S-005.

The corpora live under `fixtures/` rather than inline in this module, so that
the fictional 400-block requirement IDs never appear in Python source. The
matrix reads IDs in test files as citations; writing the fixture inline would
make this module report its own fixture data as retired references.

Why this is not a pytest-bdd binding
------------------------------------
It should be `@scenario("meta.feature", "QA-S-001 ...")`. It cannot be, yet:
`tests/features/meta.feature` is not parseable Gherkin. Line 16 reads

    @QA-S-002 @QA-005 property 6

because `testing-qa.md:158` heads that scenario `*(QA-005 property 6)*` and
`extract_features.py` splits the reference list on commas only, so the prose
"property 6" is emitted as two further tags -- and a Gherkin tag may not contain
whitespace. pytest-bdd refuses the whole file, so no step definition can bind to
any QA-S-nnn scenario. Nothing caught this because `--check` only compares
generated bytes against what is on disk, and until now no test tried to load the
feature.

Both fixes -- the heading in `docs/testing-qa.md`, or comma-splitting in
`tools/extract_features.py` -- are outside EV-22's Touches set, so this story
reports the defect rather than fixing it (AG-015). The matrix detects the class
directly: see MALFORMED_SCENARIO_REF, which fires on `testing-qa.md:158` in the
live run. Once the heading is corrected and the feature regenerates, the first
test below should become a `@scenario` binding and QA-S-001 stops being an
untested scenario.
"""

from __future__ import annotations

import shutil
import subprocess
from datetime import date
from pathlib import Path

import pytest

from tests.traceability.corpus import (
    FIXTURES,
    expected_code,
    git,
    run_default,
)
from tests.traceability.corpus import (
    corpus as _corpus,
)
from tests.traceability.matrix import (
    ALWAYS_BLOCKING,
    ENFORCEMENT_SCHEDULE,
    Severity,
    build_matrix,
    effective_threshold,
    main,
    mandated_threshold,
    strictest,
    strictness,
)


def _run(root: Path, *extra: str, today: date | None = None) -> int:
    return run_default(root, *extra, today=today)


REGRESSION = FIXTURES / "regression"


def test_qa_s_010_new_requirement_without_classification_fails_ci(tmp_path: Path) -> None:
    """QA-S-010 / EV-26 forward gate: new claims cannot enlarge the backlog."""
    rid = "CM-" + "801"  # keep fixture IDs out of the live citation scanner
    docs = tmp_path / "docs"
    tests = tmp_path / "tests"
    docs.mkdir()
    tests.mkdir()
    (docs / "coverage-methodology.md").write_text(
        f"**{rid}** — A newly introduced runtime rule with no classification.\n",
        encoding="utf-8",
    )
    test_file = tests / "test_placeholder.py"
    test_file.write_text("def test_placeholder():\n    pass\n", encoding="utf-8")
    nodeid = "tests/test_placeholder.py::test_placeholder"

    matrix = build_matrix(
        repo_root=tmp_path,
        docs_dir=docs,
        features_dir=None,
        node_ids=[nodeid],
        baseline={},
        baseline_description="fixture merge base",
        requirement_baseline={},
        regression_gate=True,
        landed_stories=frozenset(),
    )

    findings = [
        finding
        for finding in matrix.findings
        if finding.kind == "NEW_REQUIREMENT_UNCLASSIFIED"
    ]
    assert [finding.subject for finding in findings] == [rid]
    assert findings[0].severity is Severity.CRITICAL
    assert findings[0].kind in ALWAYS_BLOCKING


def test_a_new_otherwise_verified_requirement_needs_its_named_check(
    tmp_path: Path,
) -> None:
    """A future check name is classification metadata, not present evidence."""
    rid = "AC-" + "803"
    docs = tmp_path / "docs"
    tests = tmp_path / "tests"
    docs.mkdir()
    tests.mkdir()
    (docs / "architecture.md").write_text(
        "\n".join(
            [
                f"**{rid}** — A new structural requirement.",
                "",
                "> **Verification — otherwise-verified; deferred EV-90.** "
                "`pytest:tests/test_structure.py::test_missing` — "
                "The named structural check is the substitute evidence for this rule.",
            ]
        ) + "\n",
        encoding="utf-8",
    )
    (docs / "prd.md").write_text(
        f"#### EV-90 — Structural check\n**Satisfies:** {rid}\n", encoding="utf-8"
    )
    (tests / "test_structure.py").write_text(
        "def test_present():\n    pass\n", encoding="utf-8"
    )
    matrix = build_matrix(
        repo_root=tmp_path,
        docs_dir=docs,
        features_dir=None,
        node_ids=["tests/test_structure.py::test_present"],
        baseline={},
        baseline_description="fixture merge base",
        requirement_baseline={},
        regression_gate=True,
        landed_stories=frozenset(),
    )
    kinds = {(finding.kind, finding.subject) for finding in matrix.findings}
    assert ("OTHERWISE_VERIFIED_CHECK_MISSING", rid) in kinds
    assert ("NEW_REQUIREMENT_UNCLASSIFIED", rid) in kinds


def _git_corpus(tmp_path: Path, baseline: str, current: str) -> Path:
    """A real repository: `baseline` committed on branch `base`, `current` live.

    Both name a file under `fixtures/regression/`. The QA-S-001 gate reads the
    previous catalogue with `git show`, so proving it works needs real history
    rather than a hand-passed dict -- this runs the code path CI runs. The
    corpora are files rather than inline strings because the matrix reads
    requirement IDs written in test modules as citations.
    """
    root = tmp_path / "repo"
    docs = root / "docs"
    docs.mkdir(parents=True)
    (root / "collected.txt").write_text("", encoding="utf-8")
    shutil.copy(REGRESSION / "requirements.md", docs / "coverage-methodology.md")
    shutil.copy(REGRESSION / baseline, docs / "attestation-reliance.md")

    git(root, "init", "-q", "-b", "base")
    git(root, "add", "-A")
    git(root, "-c", "user.email=t@example.com", "-c", "user.name=t",
        "commit", "-q", "-m", "baseline")
    # The default baseline ref is no longer substitutable, so the fixture has to
    # provide the ref a real checkout provides rather than redirect the tool
    # away from it.
    git(root, "update-ref", "refs/remotes/origin/develop", "base")
    git(root, "checkout", "-q", "-b", "work")

    shutil.copy(REGRESSION / current, docs / "attestation-reliance.md")
    return root


def _run_as_ci(root: Path, *, baseline_ref: str = "base") -> int:
    """The argv .github/workflows/ci.yml invokes, verbatim: --mode report.

    `baseline_ref` is passed as a keyword because it is no longer a command-line
    option -- pointed at HEAD it compared the catalogue against itself, which is
    an off switch spelled differently. The fixture repository has no
    `origin/develop`, so tests redirect it through the same Python seam the
    calendar uses. The argv itself stays exactly what CI runs.
    """
    return run_default(root, "--mode", "report", baseline_ref=baseline_ref)


def test_qa_s_001_assertion_without_scenario_fails_ci(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """QA-S-001, through the CI invocation, at today's date.

    The earlier version of this test substituted `--mode enforce --fail-on
    critical`, which is not what CI runs -- so it proved the tool could fail
    without proving the pipeline would. This runs `--mode report`, the literal
    ci.yml argument, before any QA-011 stage is live.
    """
    root = _git_corpus(
        tmp_path,
        baseline="catalogue-empty.md",
        current="catalogue-unmapped.md",
    )

    code = _run_as_ci(root)
    output = capsys.readouterr().out

    assert code == 1, "a newly unmapped assertion must fail the real CI invocation today"
    assert "A-01" in output, "the failure must name the assertion, not merely count it"
    assert "NEW_ASSERTION_NO_SCENARIO" in output
    assert "outside the QA-011 schedule" in output


def test_a_pre_existing_unmapped_assertion_is_staged_not_immediate(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The distinction the gate turns on.

    An assertion already unmapped at the baseline is backlog, and backlog is
    what QA-011 stages. Failing on it today would put the build red on day one,
    which is the outcome the staging exists to avoid.
    """
    root = _git_corpus(
        tmp_path, baseline="catalogue-unmapped.md", current="catalogue-unmapped.md"
    )

    code = _run_as_ci(root)
    output = capsys.readouterr().out

    assert code == expected_code(Severity.CRITICAL), (
        "existing backlog must follow the QA-011 schedule -- green until the critical "
        "stage is live, red from it, and the expectation is derived from the schedule "
        "rather than frozen by a supplied calendar date"
    )
    assert "ASSERTION_NO_SCENARIO" in output, "and must still be reported"
    assert "NEW_ASSERTION_NO_SCENARIO" not in output


def test_repointing_an_assertion_is_a_regression_too(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Otherwise the gate is one rename away from useless.

    An assertion that existed at the baseline but has been re-pointed at a
    requirement with nothing demonstrating it is newly unmapped, whatever its
    id says.
    """
    root = _git_corpus(
        tmp_path,
        baseline="catalogue-mapped.md",
        current="catalogue-unmapped.md",
    )

    code = _run_as_ci(root)
    output = capsys.readouterr().out

    assert code == 1, "re-pointing an assertion onto an undemonstrated basis is a regression"
    assert "NEW_ASSERTION_NO_SCENARIO" in output
    assert "basis changed" in output


def test_an_unreadable_baseline_blocks_rather_than_passing(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Fail closed.

    Without the previous catalogue the gate cannot tell a regression from
    backlog. Assuming clean is how a check like this stops working without
    anyone noticing.
    """
    root = _corpus(tmp_path, "assertion_without_scenario")

    code = run_default(root, "--mode", "report", baseline_ref="no-such-ref")
    output = capsys.readouterr().out

    assert code == 1
    assert "BASELINE_UNAVAILABLE" in output
    assert "fetch-depth: 0" in output


def test_enforce_respects_the_severity_threshold(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The staging path, exercised: a medium finding, a moving threshold."""
    root = _corpus(tmp_path, "orphan_only")

    code = _run(root, "--mode", "enforce", "--fail-on", "critical")
    output = capsys.readouterr().out
    assert code == expected_code(Severity.MEDIUM), (
        "a medium finding must not fail a critical-only gate, until the schedule "
        "itself reaches medium"
    )
    assert "REQUIREMENT_NO_SCENARIO_SPEC" in output, "but it must still be reported"

    code = _run(root, "--mode", "enforce", "--fail-on", "medium")
    assert code == 1, "the same finding must fail once the threshold reaches it"


# --- QA-011 staged enforcement -------------------------------------------
#
# The schedule is compiled into the generator, not passed on the command line,
# because a ratchet any CI argument can loosen is not a ratchet. These lock the
# dates and the one-way property to the text in docs/testing-qa.md §7.


def test_schedule_matches_the_dates_qa_011_states() -> None:
    """If this fails, the spec and its implementation have drifted apart."""
    assert ENFORCEMENT_SCHEDULE == (
        (date(2026, 8, 8), Severity.CRITICAL),
        (date(2026, 9, 1), Severity.HIGH),
        (date(2026, 10, 1), Severity.LOW),
    )


@pytest.mark.parametrize(
    ("today", "expected"),
    [
        (date(2026, 8, 7), None),
        (date(2026, 8, 8), Severity.CRITICAL),
        (date(2026, 8, 31), Severity.CRITICAL),
        (date(2026, 9, 1), Severity.HIGH),
        (date(2026, 9, 30), Severity.HIGH),
        (date(2026, 10, 1), Severity.LOW),
        (date(2027, 1, 1), Severity.LOW),
    ],
)
def test_mandate_advances_by_date_alone(today: date, expected: Severity | None) -> None:
    """Expiry is by date, not by condition.

    Nothing here consults whether EV-25 merged, whether EV-26 triage finished,
    or whether any backfill happened. Slipping a story does not slip the gate.
    """
    assert mandated_threshold(today) is expected


def test_a_weaker_request_is_overridden_by_the_schedule() -> None:
    """The one-way ratchet. Asking for less than is mandated gets you the mandate."""
    threshold, why = effective_threshold(Severity.CRITICAL, date(2026, 10, 1))
    assert threshold is Severity.LOW
    assert "one-way ratchet" in why


def test_report_only_is_overridden_once_a_stage_is_live() -> None:
    """`--mode report` stops being an escape hatch the moment a date passes."""
    threshold, why = effective_threshold(None, date(2026, 8, 8))
    assert threshold is Severity.CRITICAL
    assert "overridden" in why


def test_a_stronger_request_is_honoured_and_not_walked_back() -> None:
    """Enforcing early is always allowed; the schedule is a floor, not a ceiling."""
    threshold, _ = effective_threshold(Severity.LOW, date(2026, 8, 8))
    assert threshold is Severity.LOW


def test_report_only_is_permitted_only_before_the_first_stage() -> None:
    threshold, why = effective_threshold(None, date(2026, 8, 7))
    assert threshold is None
    assert "before 2026-08-08" in why


def test_the_gate_bites_on_the_expiry_date(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """End to end through the CLI: same corpus, green before, red after."""
    root = _corpus(tmp_path, "assertion_without_scenario")

    assert _run(root, "--mode", "report", today=date(2026, 8, 7)) == expected_code(
        Severity.CRITICAL
    ), "a date before a stage cannot defer it; only the real calendar decides that"
    capsys.readouterr()

    assert _run(root, "--mode", "report", today=date(2026, 8, 8)) == 1
    output = capsys.readouterr().out
    assert "ASSERTION_NO_SCENARIO" in output
    assert "FAIL" in output


@pytest.mark.parametrize(
    ("real", "supplied"),
    [
        # The window the old sentinel left open: real calendar in the critical
        # stage, supplied date one day before it. Both mapped to rank 0, so the
        # floor never applied and enforcement switched off for all of August.
        (date(2026, 8, 8), date(2026, 8, 7)),
        (date(2026, 8, 9), date(2026, 8, 7)),
        (date(2026, 8, 20), date(2026, 1, 1)),
        (date(2026, 8, 31), date(2026, 8, 7)),
        # And the later stages, which the rank comparison happened to cover.
        (date(2026, 9, 1), date(2026, 8, 8)),
        (date(2026, 10, 1), date(2026, 9, 1)),
    ],
)
def test_today_cannot_disable_a_live_stage_through_the_cli(
    tmp_path: Path, capsys: pytest.CaptureFixture[str], real: date, supplied: date
) -> None:
    """`--today` must never weaken a mandate the real calendar has reached.

    Asserted through the CLI, at the exact point the bypass was reachable. The
    earlier version of this test only compared ranks on 1 October and so never
    touched the one stage that was broken.
    """
    root = _corpus(tmp_path, "assertion_without_scenario")

    code = run_default(
        root, "--mode", "report", real_today=real, today=supplied
    )
    output = capsys.readouterr().out

    assert code == 1, (
        f"--today {supplied} must not disable the stage live on {real}"
    )
    assert "FAIL" in output
    assert "ASSERTION_NO_SCENARIO" in output


def test_none_ranks_below_every_severity() -> None:
    """The ordering the bypass turned on.

    `None` means "block nothing" and must sit strictly below `critical`. Folding
    it onto CRITICAL is what made a live gate and no gate compare equal.
    """
    assert strictness(None) < strictness(Severity.CRITICAL)
    assert strictness(Severity.CRITICAL) < strictness(Severity.HIGH)
    assert strictness(Severity.HIGH) < strictness(Severity.MEDIUM)
    assert strictness(Severity.MEDIUM) < strictness(Severity.LOW)
    assert strictest(None, Severity.CRITICAL) is Severity.CRITICAL
    assert strictest(None, None) is None


def test_a_future_today_may_still_bring_a_stage_forward(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The legitimate use survives: rehearse September while it is August."""
    root = _corpus(tmp_path, "orphan_only")

    code = run_default(root, "--mode", "report", today=date(2026, 10, 1))
    output = capsys.readouterr().out
    assert code == 1, "a medium orphan must fail once the low stage is rehearsed"
    assert "REQUIREMENT_NO_SCENARIO_SPEC" in output


def test_no_baseline_is_not_a_command_line_option(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """PR #6 review, finding 1: QA-S-001 had a public off switch.

    `--no-baseline` disabled the acceptance criterion outright, so a newly
    unmapped assertion exited 0 for anyone who passed it. Skipping the gate is
    now reachable only from Python. `--baseline-ref` survives, because pointing
    the comparison at another commit is not the same as not comparing.
    """
    root = _git_corpus(
        tmp_path, baseline="catalogue-empty.md", current="catalogue-unmapped.md"
    )
    with pytest.raises(SystemExit) as exit_info:
        main(
            [
                "--repo-root", str(root),
                "--docs", str(root / "docs"),
                "--collect-from", str(root / "collected.txt"),
                "--no-baseline",
            ]
        )
    assert exit_info.value.code == 2, "argparse must reject the removed flag"


def test_a_missing_merge_base_fails_closed(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """PR #6 review, finding 2: the ref tip was substituted for the merge base.

    Unrelated histories and shallow clones both fail `git merge-base`. Falling
    back to the tip produced a comparison against the wrong commit while still
    labelling it a merge base, which is precisely the shallow-history case
    `fetch-depth: 0` is supposed to guard.
    """
    root = _git_corpus(
        tmp_path, baseline="catalogue-empty.md", current="catalogue-unmapped.md"
    )
    git = shutil.which("git")
    assert git is not None
    author = ["-c", "user.email=t@example.com", "-c", "user.name=t"]
    for args in (
        ["checkout", "-q", "--orphan", "unrelated"],
        ["add", "-A"],
        [*author, "commit", "-q", "-m", "unrelated history"],
    ):
        subprocess.run([git, *args], cwd=root, check=True)  # noqa: S603 - resolved path

    code = _run_as_ci(root)
    output = capsys.readouterr().out

    assert code == 1, "no merge base must block, not silently compare against the tip"
    assert "BASELINE_UNAVAILABLE" in output
    assert "no merge base" in output
    assert "fetch-depth: 0" in output


def test_changing_the_claim_text_alone_is_a_regression(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """PR #6 review, finding 3: only (id, basis) was compared.

    Rewriting what an unmapped assertion claims, while keeping its id and basis,
    is a different claim resting on the same evidence. For a closed catalogue
    (AR-003) the text is load-bearing, not decoration.
    """
    root = _git_corpus(
        tmp_path,
        baseline="catalogue-unmapped.md",
        current="catalogue-unmapped-retexted.md",
    )

    code = _run_as_ci(root)
    output = capsys.readouterr().out

    assert code == 1, "a rewritten claim on an unmapped assertion is newly unmapped"
    assert "NEW_ASSERTION_NO_SCENARIO" in output
    assert "claim text changed" in output


def test_baseline_ref_is_not_a_command_line_option(tmp_path: Path) -> None:
    """PR #6 review, final finding: the last CLI input to the gate.

    `--baseline-ref HEAD` compared the catalogue against itself and suppressed a
    committed new unmapped assertion. An arbitrary ref is not a weaker knob than
    an off switch, it *is* the off switch spelled differently. Removed, so no
    command-line input can weaken either gate: argv selects what to read and
    where to write, and nothing else.
    """
    root = _git_corpus(
        tmp_path, baseline="catalogue-empty.md", current="catalogue-unmapped.md"
    )
    with pytest.raises(SystemExit) as exit_info:
        main(
            [
                "--repo-root", str(root),
                "--docs", str(root / "docs"),
                "--collect-from", str(root / "collected.txt"),
                "--baseline-ref", "HEAD",
            ]
        )
    assert exit_info.value.code == 2, "argparse must reject the removed flag"


def test_no_cli_argument_can_weaken_either_gate(tmp_path: Path) -> None:
    """The property the three removals buy, asserted directly.

    If this fails, someone has reintroduced a knob. The check is deliberately
    against the parser rather than behaviour: a new option that happens to be
    harmless today is still the shape of every finding in this review.
    """
    import argparse
    import contextlib
    import io

    from tests.traceability import matrix as module

    parser_help = io.StringIO()
    with contextlib.redirect_stdout(parser_help), contextlib.suppress(SystemExit):
        module.main(["--help"])
    text = parser_help.getvalue()

    for forbidden in ("--today", "--no-baseline", "--baseline-ref"):
        assert forbidden not in text, f"{forbidden} must not be a command-line option"
    assert isinstance(argparse.ArgumentParser(), argparse.ArgumentParser)


def test_a_baseline_equal_to_head_is_reported_as_vacuous(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A comparison that cannot find anything must not read as a clean one.

    On a push build to the integration branch the merge base is HEAD, so nothing
    can be new. That is legitimate -- the PR was gated before it merged -- but a
    vacuous check reading as a passing one is how every other seam here went
    wrong, so it is labelled.
    """
    root = _git_corpus(
        tmp_path, baseline="catalogue-unmapped.md", current="catalogue-unmapped.md"
    )

    code = _run_as_ci(root, baseline_ref="HEAD")
    output = capsys.readouterr().out

    assert code == expected_code(Severity.CRITICAL)
    assert "this IS HEAD, so nothing can be new" in output, (
        "a self-comparison must say so rather than reporting a clean gate"
    )
